[package]
name = "tocata"
version = "0.1.0"
edition = "2024"
description = "An OpenSubsonic compatible music server"
authors = ["Óscar García Amor <ogarcia@connectical.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/ogarcia/tocata"
readme = "README.md"
keywords = ["opensubsonic", "music", "server", "audio", "streaming"]
categories = ["multimedia::audio", "web-programming::http-server"]

[dependencies]
anyhow = "1.0"
sqlx = { version = "0.9", default-features = false, features = ["runtime-tokio", "tls-none", "sqlite", "macros", "migrate", "chrono"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
